### PR TITLE
Fixing issues with magic items not displaying

### PR DESCRIPTION
**Pull request by YakFromStateFarm**
Fixing issues with magic items not displaying. The main problem was a rename to the module, going from "magicitems" to "magic-items-2". That has been fixed up in the code and rerolled.

### CODE REVIEW

**Comment by PwQt** [comment]
As "owner" of magic-items-2 I'd highly recommend for this to work both for "old" and "new" version.

**Comment by YakFromStateFarm** [comment]
> As "owner" of magic-items-2 I'd highly recommend for this to work both for "old" and "new" version instead of only the new version.

Good call. Ill make add a change where it looks for either magicitems or magic-items-2.

**Comment by YakFromStateFarm** [comment]
This should be good to go for the minor magic items fix. As I said, it was just an issue with the package names for the new MagicItems2 package being different. I made sure that both versions work as discussed above.

**Comment by Larkinabout** [comment]
Thanks, will take a look this week.

**Pull request merged**
